name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [l1, l2, l3]
    steps:
      - name: echo a string
        run: echo 'Hello you all'
      - if: ${{ matrix.containers }} == 'l1'
        run: echo "Hello L1"
      - if: ${{ matrix.containers }} == 'l2'
        run: echo "Hello L2" 
      - if: ${{ matrix.containers }} == 'l3'
        run: echo "Hello L3" 

      - name: multiple script
        run: |
          node -v
          npm -v
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python  
  run-windows-commands:
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: Directory PowerShell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash   